language: go
go: 
 - 1.10.x
 - 1.11.x
 - 1.12.x
 - tip
sudo: false
script:
 - go test -v -race ./... -coverprofile=profile.cov
after_success:
 - go get -v github.com/mattn/goveralls
 - goveralls -coverprofile=profile.cov -service=travis-ci
